# Generated by Django 5.0.7 on 2024-07-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterField(
            model_name="question",
            name="question_no",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="number_of_questions",
            field=models.IntegerField(default=0),
        ),
    ]
